### ISSUE TITLE
Auto play doesn't working with angular 4.3.0

### ISSUE THREAD

**Issue by MuhammadShaban** [JayChase/angular2-useful-swiper#28]
after update from angular 4.2.6 to 4.3.0 Auto play doesn't working with angular 4.3.0
if i downgrade angular to 4.2.6 it's working

this option is working perfect with 4.2.6
`swiper: Object = {
        pagination: '.swiper-pagination',
        paginationClickable: true,
        initialSlide: 0,
        slidesPerView: 1,
        spaceBetween: 30,
        loop: true,
        autoplay: 3000,
        autoplayDisableOnInteraction: false
};`

**Comment by thomsebastin** [comment]
I have a question that I didn't want to create a new thread for - speaking of angular 4, are you also supporting `angular 4`? Would be better if you could add compatibility with `ng-universe` too as there are no decent carousel alternatives available at the moment.

**Comment by JayChase** [comment]
@MuhammadShaban I have a plunk on Angular 4.3 which is working with your config http://embed.plnkr.co/OiX7kC/. I am using v 8.1.2 of zone.js the latest version seems to have a few issues.

**Comment by JayChase** [comment]
@thomsebastin it works with Angular 4. All the demos are currently on 4.2.6. It supports universal in that it won't error if rendering on the server side.

**Comment by MuhammadShaban** [comment]
@JayChase you are right the problem with zone.js@0.8.13 not with angular
i'm downgrade to zone.js@0.8.12 and every thing now working perfect 
thanks
