### ISSUE TITLE
How to access methods within the component?

### ISSUE THREAD

**Issue by thomsebastin** [JayChase/angular2-useful-swiper#29]
I know that I can add properties in `config`, but let's say if I want to `destroy` (by using `destroy` method) the carousel based on some condition, how do I do that? Can you provide us an example of how to use a method from within a component? @JayChase

**Comment by JayChase** [comment]
The swiper object is available as a property on the component so you can using a local template to get to it in the component and call any API function you need on it. https://plnkr.co/edit/Oqx8Hw?p=preview
