### ISSUE TITLE
Angular-cli sourceMap not found warning

### ISSUE THREAD

**Issue by tarundhillon** [JayChase/angular2-useful-swiper#33]
Hi,

Instead of directly embedding the swiper.js file html file I have included it in the angular-cli.json as an external script. The lib works fine but I get the following warning during compilation  and I was wondering if you know how to get rid of this 

> WARNING in ./~/raw-loader!./~/source-map-loader!./src/script/swiper.min.js
> (Emitted value instead of an instance of Error) Cannot find SourceMap 'maps/swiper.min.js.map': Error: Can't resolve './maps/swiper.min.js.map' in '/.../..src/script'
>  @ ./~/script-loader!./src/script/swiper.min.js 1:110-391
>  @ multi script-loader!./src/script/swiper.min.js

or is there a better way of including the file instead of html. 

Thanks

**Comment by JayChase** [comment]
I've updated the readme with details of how to do the npm install of swiper. Also v 5.0.0 has improved typings. Hopefully these should help.
