### ISSUE TITLE
please update the package json for material modules

### ISSUE THREAD

**Issue by aarustar** [JayChase/angular2-useful-swiper#35]
node_modules/@angular/material/typings/tooltip/tooltip.d.ts(14,132): error TS2307: Cannot find module '@angular/cdk/overlay'.
test/demo/demo.component.spec.ts(44,32): error TS2339: Property 'forRoot' does not exist on type 'typeof MaterialModule'.

**Comment by JayChase** [comment]
These are updated now in the latest version.
