### ISSUE TITLE
Swiper reference went lowercase in 5.0.0?

### ISSUE THREAD

**Issue by alfupe** [JayChase/angular2-useful-swiper#38]
Hi there,

Lets say we set a swiper's reference in the template (in the example below is #swiperRef).
```html
<swiper [config]="swiperConfig" #swiperRef>
        <div class="swiper-wrapper">
            <article class="swiper-slide">
...
```
We use the ref to make an action:
```html
<a href="#" (click)="changeSlide($event, 10, swiperRef)">...
```
**In the component** we use the reference, for example to call a slideTo:
```typescript
changeSlide(event, slideId, swiperRef: SwiperComponent): void {
        event.preventDefault();

        swiperRef.swiper.slideTo(slideId); ///<-------
    }
```
I suppose that since version 5, something has changed because I had to update every `.Swiper` call to `.swiper` (in lowercase). It isn't it?

I somebody is updating from v4 to v5 and get a lot of undefined references, here it is!

**Comment by JayChase** [comment]
Sorry about that. You are right it was the breaking change form 4.x to 5. I updated the document and samples but reading back it isn't that obvious.

**Comment by alfupe** [comment]
Thanks to you for the work you have done in this module!
