### ISSUE TITLE
Pagination and changing a slide by clicking on arrow doesn't work

### ISSUE THREAD

**Issue by jbojcic1** [JayChase/angular2-useful-swiper#39]
I followed your installation instructions for angular cli, but I don't see any pagination and I can't change slide by clicking to an arrow (I can change it with drag and drop). Is it possible that something is missing in the docs or I am doing something wrong?

**Comment by Acika00mk** [comment]
Same issue trying to figure out, 
the demo is working but not locally 
http://plnkr.co/edit/qM4jHG?p=preview

**Comment by Acika00mk** [comment]
update : 
change the version of swiper in package.json to 3.3.1 and it will work

**Comment by schankam** [comment]
Damn... Man, this should be in the documentation of the plugin... I lost like 2 days to figure out why it was not working T_T

**Comment by tomfloresa** [comment]
@Acika00mk thanks!

**Comment by JayChase** [comment]
Thanks for everyone's help with this. I've updated the docs to specify swiper 3.4.2 as the version to use. It will be a while before I get round to supporting v 4.0.0 as I want to take the opportunity to move the project into angular-cli at the same time.
