### ISSUE TITLE
onClickNext is not firing

### ISSUE THREAD

**Issue by sumithmano** [JayChase/angular2-useful-swiper#42]
Everything is working except the callbacks.

`this.usefulSwiper.swiper.slideNext(); `

is working fine but when I use 

```
this.usefulSwiper.swiper.onClickNext((event) => {
    console.log('slide changed');
});
```

Error occurs in the console when the event triggers.

> ERROR Error: Uncaught (in promise): TypeError: e.preventDefault is not a function
TypeError: e.preventDefault is not a function
at Swiper.s.onClickNext (scripts.bundle.js:1415)

I used angular cli to create the project structure.

![screen shot 2017-11-03 at 1 49 38 pm](https://user-images.githubusercontent.com/25614817/32364993-ee2ec8b4-c09d-11e7-9552-6bf844862698.png)

![screen shot 2017-11-03 at 1 49 57 pm](https://user-images.githubusercontent.com/25614817/32364991-ede77acc-c09d-11e7-8444-69382af97616.png)

The place where it is crashing is the e.preventDefault

**Comment by sumithmano** [comment]
This is not a issue. I misunderstood the api.

**Comment by stubbsy345** [comment]
Hi I don't suppose you know the fix I am having same issue.
