### ISSUE TITLE
SCRIPT1002: Syntax error with angular

### ISSUE THREAD

**Issue by kovaletsyurii** [JayChase/angular2-useful-swiper#59]
I am use latest ngx-useful-swiper with angular 7 and IE 11 throw error with syntax error to class declaration:
```
class Dom7 {
}
```
Can you please help, how need I transpile this using angular-cli?

**Comment by kovaletsyurii** [comment]
I am going to fix this with additional babel transpile step before build script running, but maybe better way is creating repo with es5 transpiled Dom7 library

**Comment by kumare1982** [comment]
I am facing the same issue. Is there any fix for this?

**Comment by kovaletsyurii** [comment]
> I am facing the same issue. Is there any fix for this?

You can use my version of DOM7 library, I just transpile them https://github.com/kovaletsyurii/dom7-es5
