### ISSUE TITLE
Can't resolve "./node_modules/swiper/css/swiper.css"

### ISSUE THREAD

**Issue by massimiliamanto74** [JayChase/angular2-useful-swiper#83]
When I add styles inclusion in Angular.json (angular 9) it return the error in subject

**Comment by leo6104** [comment]
Instead of adding 
```
"./node_modules/swiper/css/swiper.css" 
```
in angular.json 

put 

```
"./node_modules/swiper/swiper.scss"
```

**Comment by massimiliamanto74** [comment]
Tanks @leo6104 I did it but it is not the problem.
I have investigated in deep and I found that the problem is on *ngIf=myVariable.
I mean:

`<div *ngIf='myVariable'><mySwiper ..... ></mySwiper></div>`

on init, myVariable = false, then on AfterViewInit, i subscribe an Observable (BehaviourSubject) and when the myVariable=>true, the swiper is showned but slides doesn't move on Arrow or dot click, however the autoplay works.

**Comment by massimiliamanto74** [comment]
thanks @leo6104
